nipreps/smriprep

smriprep/workflows/surfaces.py

[FIX] Add ``-cw256`` flag for images with FoV > 256 voxels

---

.circleci/ds054_outputs.txt
Dockerfile
requirements.txt
smriprep/__about__.py
smriprep/cli/run.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/norm.py
smriprep/workflows/outputs.py

This PR makes more flexible the spatial normalization, setting a list of target templates as an iterable for the new spatial normalization workflow (#72).
This PR also makes use of the refactored reports of poldracklab/niworkflows#344, which allow rendering several spatial normalization reportlets. To do so, the nomenclature of reportlets has been adapted and resembles a BIDS-like organization.

ENH: Support for multiple ``--output-spaces``

---

.circleci/config.yml
smriprep/cli/run.py

Before this change, when ``--template`` was set, sMRIPrep would not
check whether ``--output-spaces`` was also specified too. As a result,
instead of replacing the default ``MNI152NLin2009cAsym`` template, the
new identifier given with ``--template`` was inserted at the front of
the spaces.
In other words:
```
smriprep ... --output-spaces MNI152NLin2009cAsym --template MNI152Lin
```
and
```
smriprep ... --template MNI152Lin
```
would both end up understanding ``['MNI152Lin', 'MNI152NLin2009cAsym']``,
whereas with the original behaviour, one would expect to only have
``['MNI152Lin']`` when using the second command.
This PR addresses such issue (and updates the CircleCI test not to use
``--template`` as I have checked locally this works as expected).

FIX: resolve behavior when deprecated ``--template`` is given

---

requirements.txt
smriprep/__about__.py
smriprep/workflows/anatomical.py

This PR inserts a validation node right after creating the anatomical
template and pins niworkflows to use a revised version of the
antsBrainExtraction workflow that controls consistency of headers.
Fixes #82. Required by poldracklab/fmriprep#1615.

FIX: Keep header consistency along anatomical workflow

---

smriprep/workflows/norm.py

Although spatial normalization of the T1w image was being done using
resolution-1 of the template, subsequent reportlet generation and
resampling for preservation under ``anat/`` would follow whatever
res-X modified given within ``--output-spaces``.
Since the ``--output-spaces`` argument is thought to mandate over
BOLD outputs only, the previous implementation was a problem as it
imposed a lower resolution when it wasn't really appropriate.
This PR will generate high-resolution preprocessed anatomicals
(reportlet and derivative) in any case.
Spatial normalization will keep working the same way (i.e., it will
use res-1, except if `--sloppy` was given in which case it will use
res-2).

ENH: Use proper resolution in anatomical outputs

---

.circleci/config.yml

PyPI deployment failed. Copying the deployment test and just adding a `twine upload` step.

CI: Fix PyPI deployment

---

smriprep/interfaces/templateflow.py
smriprep/workflows/anatomical.py
smriprep/workflows/norm.py
smriprep/workflows/outputs.py

Spatial normalization defines selected ``--output-spaces`` as an
iterable to the workflow.
This PR removes several ad-hoc function nodes and replaces them with a
new nipype interface to query templates.
These changes will facilitate concluding #107.

ENH: Reduce friction when iterating over target templates

---

.circleci/ds005_outputs.txt
smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py

Add a datasink to include a `_from-fsnative_to-T1w_mode-image_xfm.txt`
file that maps coordinates from the original T1w image into from FS'
conformed space coordinates.
Another improvement to ease #107 .

ENH: Write out the fsnative-to-T1w transform

---

smriprep/interfaces/reports.py
smriprep/workflows/anatomical.py
smriprep/workflows/norm.py
smriprep/workflows/outputs.py
smriprep/workflows/surfaces.py

This PR delays report generation to the ``anat_report_wf`` workflow which is staged at the end. This decoupling will allow creating reportlets from existing derivatives in the context of #107. The most immediate result of decoupling is visible when connecting inputs to ``anat_report_wf`` - most of them are sourced from the ``outputnode`` and the normalization and surfaces reports are not passed in anymore.
For the generation of the surfaces report, the ReconAllRPT interface is dropped, and a new lightweight interface based on ``SimpleInterface`` is included.

ENH: Decoupling anatomical reports

---

.circleci/config.yml

Scipy doesn't have a Python 3.8 wheel yet, and building it is a pain. Dropping pytests back to 3.7 for now.

CI: Run pytests on Python 3.7 for now

---

.circleci/config.yml

Seems like replacing the docker save/load approach with a local registry run on the same machine allows us to make the main build job ~8min lighter and smoke tests builds ~6min lighter.
This is probably not a big deal time-wise, but I think this approach is more reliable than the docker save/load, and will escalate better if CircleCI opens up to having service jobs or some such.
This PR also revises the artifacts being collected - which were too many for successful runs (including the work directory and freesurfer folder).
The idea is to test how this works for sMRIPrep and then propagate to fMRIPrep and other projects if things look good.

CI: Optimize CircleCI using a local docker registry instead docker save/load

---

.circleci/config.yml

We were not running very strict tests, and that ended up submitting a version 99.99.99 to pypi.

FIX: Build smriprep-docker like fmriprep-docker

---

smriprep/interfaces/templateflow.py
smriprep/workflows/anatomical.py
smriprep/workflows/norm.py
smriprep/workflows/outputs.py

[A recent change](https://github.com/poldracklab/smriprep/commit/4d06de1da75b9bbabf913bb8088a74a076f14b5e#diff-22ed5ba333295a58e8031657cba4de41) is provoking [this error](https://github.com/poldracklab/fmriprep/pull/1827#issuecomment-542502578). This PR fixes the problem.

FIX: Normalization workflow API - provide bare template names

---

smriprep/cli/tests/test_utils.py
smriprep/cli/utils.py

fix: empty specs for legacy/nonstd spaces

---

smriprep/workflows/surfaces.py

Reported in [Neurostars #5564](https://neurostars.org/t/autorecon-surfs0-mrisread-rh-white-could-not-open-file/5564), T2 processing in FreeSurfer runs into a data dependency failure because we're running `-T2pial` in `-autorecon-hemi` stage, while it needs to run immediately before `-cortribbon`.
It's pretty coarse. There's a part that has to be run serially, and then a part that can be parallelized across hemispheres. By using `-parallel`, we can get the parallelism, at the cost of 2x cores for the whole process. If nothing in [`-T2pial`, `-surfvolume` or `-cortribbon`](https://github.com/freesurfer/freesurfer/blob/2beb96c6099d96508246c14a24136863124566a3/scripts/recon-all#L4147-L4391) can take advantage of OpenMP parallelism, then this will be a 2-core job, which seems acceptable. If …

FIX: Use T2/FLAIR refinement at cortribbon stage

---

Dockerfile
MANIFEST.in
setup.cfg
versioneer.py

Addresses the problem that sMRIPrep inside containers gives version 0+xxx

FIX: Package version incorrect within Docker image

---

smriprep/__main__.py

This will make it easier to do things like:
```
docker run --entrypoint=coverage poldracklab/smriprep:latest run -m smriprep ...
```
Because coverage takes scripts by default, the alternative is to hard-code the full path.

ENH: Add smriprep.__main__ to allow python -m smriprep

---

smriprep/workflows/surfaces.py

Intended for a bug-fix release 0.4.2.
Closes #160.
Ref: #29, #36.

FIX: Calculate FoV with shape and zooms

---

.circleci/config.yml

- Don't deploy to Pypi if ``build_docs`` fails (close #150)
- Do not cache reportlets folder (see https://github.com/poldracklab/smriprep/pull/159#issuecomment-579835244)

FIX: Improvements to the CircleCI workflow

---

.circleci/config.yml
.circleci/ds005_run.sh
.circleci/ds054_run.sh
setup.cfg
smriprep/cli/run.py
smriprep/data/io_spec.json
smriprep/interfaces/templateflow.py
smriprep/utils/bids.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/outputs.py

These changes modify the workflow construction function ``init_anat_preproc_wf`` to add a checkpoint on the new named argument ``existing_derivatives`` at the beginning of the process.
When ``existing_derivatives`` is a dictionary containing all the anatomical derivatives to be computed, then the workflow is short-cut and only the reportlets are re-generated.
Other changes in this PR include:
Closes #105.

ENH: Enable anatomical fast track reusing existing derivatives

---

setup.cfg

This bumps the minimum niworkflows version to be in line with fmriprep 20.1.x

MAINT: bump dependencies

---

smriprep/workflows/anatomical.py

all other connections of `brain_extraction_wf.outputnode.bias_corrected` call `_pop()` to ensure singular file is passed. this PR apply that principle to the outputnode as well.

FIX: ensure bias_corrected is single file, not list

---

smriprep/utils/misc.py
smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py

Postponing this relabeling created a deviation of the derivative written
out to the hard disk and the actual file passed on by the outputnode.
This PR should serve as a basis for the elimination of FSL FAST in
``recon-all`` -based workflows (cc/ @mgxd):
- FAST and the new tailgating node should be moved inside the if
branch for ``--fs-no-reconall``
- The LUT mapping function should be reused to remap FS's ``aseg``
into a 3-tissue brain segmentation.
Resolves: #176
Related: #170
Related: poldracklab/fmriprep#1175

FIX: Correct the ``dseg`` labeling from FSL FAST earlier

---

smriprep/workflows/anatomical.py

This PR restructures the anatomical workflow so that the ``recon-all``
based graph does not execute FSL FAST, and rather projects the
``aseg`` segmentation to a 3-tissue brain segmentation with labels
according to BIDS.
This should provide the confounds workflow of *fMRIPrep* with smoother
(and probably more accurate) regions (e.g., for aCompCor calculations).
On the long run, we hope this will add some extra run-to-run
reproducibility to the aCompCor calculations.
Resolves: #170

ENH: Execute FSL FAST only with ``--fs-no-reconall``

---

smriprep/workflows/anatomical.py

This PR amends reminding problems in the label assigments of tissue
probability maps after #183.
Resolves: #189
References: #183

FIX: Revise tissue probability maps connections and order

---

smriprep/workflows/base.py
smriprep/workflows/outputs.py

Only keep it for the individual run's affine to the T1w template.
Resolves: #191.
Amends: #183.
Relates: #188.

FIX: Dismiss ``session`` entity on most of anatomical derivatives

---

smriprep/workflows/norm.py

Goes with poldracklab/fmriprep#2147

FIX: ``MultiLabel`` interpolations should not use ``float=True``

---

.circleci/config.yml
docs/conf.py
smriprep/workflows/surfaces.py

Closes #154.
As noted in #154, if fsnative is not pre-aligned with the T1w template fMRIPrep produces, aparc/aseg do not get properly aligned, and due to using FreeSurfer outputs to refine the brainmask, everything suffers.
This first pipes the `t1w2fsnative_xfm` to the segmentation workflows (`init_segs_to_native_wf`). This workflow had used `mri_label2vol` + `mri_convert`. The `mri_label2vol` was already converting to NIfTI, so I dropped `mri_convert`.
I manually confirmed that using `mri_label2vol` with the *inverse* LTA gets the alignment right.
I also noticed that `mri_label2vol` has label, annotation and volume modes. Since `aseg.mgz` and `aparc+aseg.mgz` are already volumes (`.mgz`, rather than `.label` or `.annot`), I checked whether `mri_vol2vol` could be used.
That also worked. …

FIX: Use t1w2fsnative_xfm to resample segmentations

---

smriprep/cli/run.py

Addresses the problem discussed in nipreps/niworkflows#538 with a backwards compatible change (i.e., the canary function should work regardless of the nipreps 1.2.x used).
Closes #203.

FIX: Adapt to the new FS canary interface (backwards compatible)

---

smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/norm.py
smriprep/workflows/outputs.py
smriprep/workflows/surfaces.py

This change enforces all `init_*` workflows to be keyword-only. We've generally stuck by the practice anyways when initializing workflows
https://www.python.org/dev/peps/pep-3102/

RF: Make workflows keyword-only (PEP 3102)

---

smriprep/data/io_spec.json

Resolves a problem with the I/O specification where the order of standard tissue labels (GM, WM, CSF) was incorrect.

FIX: Ordering of ``probseg`` maps with anatomical *fast-track*

---

smriprep/utils/misc.py
smriprep/utils/tests/test_misc.py
smriprep/workflows/anatomical.py

This is a proof of concept for what was discussed in #41
A few things to note:
- The only way `IsRunning` files will be removed is if they have a modification time of `> 1 day/24 hours/86400 seconds` from the time of running.
- This is implemented as an overwrite Node, meaning it will always rerun.
- The function always returns the `subject_dir`, which is then passed to `surface_recon_wf` to ensure any necessary cleaning has occured.
I will add some testing if we decide to go this route

ENH: Add function to handle stale IsRunning files

---

wrapper/smriprep_docker.py

Adding an option to the wrapper to omit the "-it" argument to docker, which avoids crashes in non-interactive environments (https://github.com/nipreps/smriprep/issues/209)

Add --no-tty option to smriprep-docker.py

---

.circleci/ds005_outputs.txt
.circleci/ds054_outputs.txt
smriprep/cli/run.py
smriprep/utils/bids.py

From a review of the expected outputs, the artifacts of a recent build, and the current draft of [BEP-011](https://bids-specification.readthedocs.io/en/bep011/), sMRIPrep produces conformant derivatives, with the exception of the dataset description. This PR updates the description, and adds a `.bidsignore` file to make life easier on the validator.
Closes #210.

ENH: Update derivative description, bidsignore for derivative

---

.circleci/ds054_outputs.txt
.circleci/ds054_run.sh
smriprep/cli/run.py
smriprep/interfaces/templateflow.py
smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py

Generates the anatomical derivatives in standardized volumetric spaces
directly within the derivatives workflow, instead of taking them as
inputs.
The spaces object must be passed in to determine the full specification
of output spaces.
Has some node duplicity for the generation of the reportlet, but I think
this implementation is much more clear, and follows fMRIPrep's patterns.
Resolves: poldracklab/fmriprep#2226.
Supersedes: #218.

FIX: Generate anatomical conversions with full spec from ``--output-spaces``

---

.circleci/config.yml

`test_deploy_pypi` is failing because of dependency resolution failure in Python 3.7. Could find a workaround to fix it, but it's just for checking sdists/wheels, so it's not an issue we're responsible for. It's somewhere between the pip resolver and twine's dependency tree.
3.8 support is universal, so I can't see any reason to hold on to 3.7, so I bumped all of our `python:<ver>` images up.

CI: Update Python images to 3.8.5

---

.circleci/config.yml

After running black, quotes of ``__version__`` changed from single to double,
and the ``sed`` expression we were using on CircleCI to set the actual version
stopped working as it expected single quotes.
Resolves: #234.

FIX: Sturdier version check of sMRIPrep-wrapper package

---

.circleci/config.yml

It was a waste to cache it in the ``get_data`` job, load the appropriate cache
before ``docker run``, and finally dismiss its existence not binding the path.
This will evaluate whether the TemplateFlow home directory can be correctly
mounted from the host when using containers.
I would advocate for not overloading the docker image with pre-cached templates
and advise users to bind the appropriate path from their host (#202).
Alternative: #202.

MAINT: Mount TemplateFlow's home directory in CircleCI tests

---

.circleci/config.yml
setup.cfg

Changes in the working directory in master are causing reuse problems here.

CI: Use separate fallback cache for maint/0.7.x

---

smriprep/interfaces/templateflow.py

UNCInfant template currently fails, since the brain mask contains `label-brain` instead of `desc-brain`. AFAIK, `label` is the preferred entity for this.
This is a quick fix, but looking through the code, I think the `TemplateFlowSelect` interface as a whole needs a substantial rework. Was it envisioned as a nipype wrapper for `templateflow.api.get`?

FIX: Account for label entity when querying brain mask

---

smriprep/workflows/anatomical.py

Closes #254.
Open question: This changes the workflow graph, but only by changing the branch that is followed. Is this acceptable to put in 0.7.x for use in fMRIPrep 20.2.x (ref [Versions Matrix](https://www.nipreps.org/devs/versions/#fmriprep))?

FIX: Revert to FAST

---

.github/workflows/pythonpackage.yml

Direct invocations of setup.py are discouraged by everybody including setuptools developers. The contemporary equivalents of these are pip installing, so let's just test those.

CI: Drop test for direct invocation of setup.py

---

.circleci/config.yml

Doc dependency installation step shows:
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
sphinx-rtd-theme 1.0.0 requires docutils<0.18, but you'll have docutils 0.18 which is incompatible.
Successfully installed MarkupSafe-2.0.1 PyWavelets-1.1.1 PyYAML-6.0 Pygments-2.10.0 alabaster-0.7.12 babel-2.9.1 bids-validator-1.8.4 bleach-4.1.0 ci-info-0.2.0 click-8.0.3 colorclass-2.2.0 cycler-0.11.0 defusedxml-0.7.1 docopt-0.6.2 docutils-0.18 entrypoints-0.3 etelemetry-0.2.2 h5py-3.5.0 imageio-2.10.2 imagesize-1.2.0 ipython-genutils-0.2.0 isodate-0.6.0 …
```

CI: Use latest pip to ensure better dependency resolution

---

smriprep/interfaces/freesurfer.py

FreeSurfer has some bugs with limiting processing that requires both hemispheres to have completed. Changing `-autorecon-hemi lh` to `-autorecon-hemi lh -lh-only` (and likewise for rh) resolves the issue. We might even be able to simplify the workflow with this fix, but that's for another day.

FIX: Override nipype handling of recon-all hemi input

---

wrapper/smriprep_docker.py

With a sufficiently wide terminal, `argparse` can decide to rearrange the usage string. Instead of splitting on lines, split on whitespace. We're still looking for the last three items.

WRAPPER: Fix help merge in smriprep-docker

---

.github/workflows/pythonpackage.yml

Until scikit-image, h5py and pytables have 3.11 wheels on PyPI, it's not worth testing it.

CI: Set max Python version to 3.10

---

wrapper/smriprep_docker.py

WRAPPER: Update patch location, use --patch syntax

---

smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/outputs.py

The approach taken here is to merge the T2w images in exactly the same way as T1w images (N4 -> mri_robust_template) and then bbregister. This is the approach taken by `recon-all`, and seems the safest way to do this without running brain extraction first. Therefore this is only available if FreeSurfer is run.
Closes #69.
We could probably throw in #13 at the same time and pass the merged T2w image to FreeSurfer...

ENH: Merge T2w images and coregister to T1w template

---

.circleci/ds005_outputs.txt
smriprep/data/io_spec.json
smriprep/interfaces/workbench.py
smriprep/utils/bids.py
smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py
smriprep/workflows/surfaces.py

#321 has a lot of style changes and some conflicts with master. I tried to pull out the relevant changes into a single commit.
@madisoth could you test this branch? If you're happy with it, you can force-push it to your branch and we can go from there.

ENH: Add cortical ribbon workflow

---

setup.cfg
smriprep/conftest.py
smriprep/interfaces/cifti.py
smriprep/interfaces/freesurfer.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/outputs.py
smriprep/workflows/surfaces.py

Currently inaccessible to smriprep itself because I don't want to add and test a CLI option. Could probably go into a bug-fix release if someone cares about it before the next minor release.

ENH: Enable resampling morphometrics to fsLR CIFTI-2 files

---

smriprep/cli/run.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/norm.py

This adds `sloppy` to the anatomical workflow (and all necessary children), and distinguishes between `debug`, which produces intermediate outputs to facilitate debug certain preprocessing steps (currently none), and `sloppy`, which sacrifices algorithmic performance for speed.
ATM, `debug` has no options, but I left it open to future additions.
Needed for https://github.com/nipreps/nibabies/pull/290

MNT: Add `sloppy` argument to workflows, distinguish from `debug`

---

CHANGES.rst
setup.cfg

Ready for release, pending passing tests in https://github.com/nipreps/fmriprep/pull/3011.

REL: 0.12.0

---

docs/conf.py
get_version.py
setup.py
smriprep/cli/run.py
smriprep/interfaces/freesurfer.py
smriprep/interfaces/reports.py
smriprep/workflows/surfaces.py

Apply [pyupgrade](https://github.com/asottile/pyupgrade) suggestions:
```
pyupgrade --py38-plus
```

MNT: apply pyupgrade suggestions

---

.circleci/config.yml
docker/files/freesurfer7.3.2-exclude.txt

DOCKER: Include 3T18yoSchwartzReactN32 FreeSurfer atlas in image

---

.circleci/config.yml
Dockerfile
env.yml
requirements.txt

Bringing things up-to-date with fMRIPrep.
Closes #354.

MNT: Update installation environment

---

.circleci/ds005_outputs.txt
smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py

Follow-up to #358 in smriprep-next. This continues to save the initial `space-fsLR_desc-reg_sphere.surf.gii` and adds `space-fsLR_desc-msm_sphere.surf.gii`.

ENH: Save msm registration sphere as desc-msm_sphere.surf.gii

---

.circleci/config.yml
.circleci/ds005_outputs.txt
smriprep/data/io_spec.json
smriprep/utils/bids.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/outputs.py
smriprep/workflows/surfaces.py

Not much to say. Moved some of the surface conversion into first-order fit, even though they are easy to calculate post hoc because they are needed if msmsulc is used. Initially tried to make some of it conditional, but it made it annoying to construct the complement after the fact. A few extra surfaces in the anatomical derivatives are not our biggest problems, space-wise.

ENH: Add sphere registration to fit workflow, check for precomputed

---

smriprep/interfaces/workbench.py
smriprep/workflows/surfaces.py

This should address issues raised in https://github.com/nipreps/fmriprep/issues/3092

FIX: Add surface-modify-sphere call to catch potential sphere elongation

---

smriprep/interfaces/surf.py
smriprep/workflows/surfaces.py

We weren't applying the fsnative2t1w_xfm to the surfaces when converting. Also updated the transform to nitransforms directly, and invert the fsnative2t1w mapping, since that mapping maps points in T1w space to fsnative and we need to go the other way.
Confirmed that surfaces now align. This is needed to get CIFTI resampling working correctly, as that depends on GIFTIs.

FIX: Update surfaces with fsnative2t1w_xfm

---

wrapper/smriprep_docker.py

No need to pass a list literal to set(), directly use a set literal.

MNT: Use a set literal, not a list literal

---

Dockerfile

It's possible that we're using AFNI through some niworkflows pipeline, but I don't think so. This will reduce the container size a little and build time by a bit.

MNT: Remove AFNI from smriprep docker container

---

smriprep/interfaces/freesurfer.py
smriprep/workflows/surfaces.py

This one's a little weird, due to the multiple inheritance and also the inefficiency of multithreading in `mris_expand`. 
I noticed `midthickness` taking a long time while running tests, and I was pretty sure I'd seen that it could be parallelized. 
From watching `htop` and running `mris_expand` with a set of `OMP_NUM_THREADS` values, I see that generally you get about 65-75% core utilization, generally a bit under. We therefore overallocate threads by about 50% to make the core usage match the desired number of threads, occasionally peaking over but mostly sitting a bit under. This works pretty well for 2-12 desired threads (3-18 `OMP_NUM_THREADS`), but seems almost completely limited after that, with 24 threads utilizing maybe 13 cores at best. Therefore, I set this to max out at 12 for …

ENH: Annotate mris_expand with thread usage

---

smriprep/interfaces/gifti.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/outputs.py
smriprep/workflows/surfaces.py

This is necessary to allow fMRIPrep to pick and choose workflows based on user requests.
This also replaces the old morphometry CIFTI-2 files with ones resampled along the lines of HCP.

RF: Split template and fsLR resampling and sinking into isolated workflows

---

smriprep/workflows/anatomical.py
smriprep/workflows/tests/test_anatomical.py

Realized I'd started on this, so finished it off. It's just meant to exercise the workflow building logic.

TEST: Add smoke tests for main anatomical workflows

---

smriprep/workflows/anatomical.py
smriprep/workflows/base.py

ENH: Add T2w/FLAIR usage to boilerplate

---

smriprep/workflows/anatomical.py
smriprep/workflows/tests/test_anatomical.py

Small fix while writing the smoke tests in #390 turned out to be a typo. The issue was that we weren't using the `t1w_buffer` as a source for T2w preprocessing, so that if you had a preprocessed T1w image but an unprocessed T2w image, you'd try to grab the T1w from the wrong place. And I typed it wrong, and some of these checks are only found at workflow expansion.
Added workflow expansion to the test to catch this.
Fixes #398.

FIX: T1w_preproc -> t1w_preproc

---

smriprep/data/atlases/L.atlasroi.59k_fs_LR.shape.gii
smriprep/data/atlases/R.atlasroi.59k_fs_LR.shape.gii

Retrieved from https://github.com/DCAN-Labs/DCAN-HCP/tree/main/global/templates/170494_Greyordinates.
Necessary to resolve https://github.com/nipreps/fmriprep/issues/3178.

ENH: Add 59k atlases

---

smriprep/interfaces/templateflow.py
smriprep/utils/misc.py
smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py

This addresses https://github.com/nipreps/fmriprep/issues/3240, a few changes were necessary:
- Fetch templates during workflow creation - without this, I was still observing race conditions causing the T1w/brain mask files to be empty (not yet gotten through `templateflow.api.get()`)
- Add `sloppy` parameter to `init_template_iterator_wf`, since the T1w/brain mask's resolution (used in [`SpatialNormalization`](https://github.com/nipreps/niworkflows/blob/6edfb38f1aa6c706c8a4942ebadd9041738978b9/niworkflows/interfaces/norm.py#L130)) depends on this parameter as well.
I stripped out most of the logic in `TemplateFlowSelect` to avoid duplicating the behavior, since it is essentially linked.

FIX: Fetch templates during workflow construction

---

pyproject.toml
requirements.txt
smriprep/cli/run.py

see https://github.com/nipreps/smriprep/pull/393#issuecomment-2010268610

[FIX] Require recent templateflow, select correct aparc dseg.tsv

---

.github/workflows/pythonpackage.yml

Merge commits often break the `[skip ci]` check. Also the test logs are full of complaints about missing `FSLOUTPUTTYPE`.

CI: Small cleanups to GHA

---

wrapper/pyproject.toml
wrapper/setup.cfg
wrapper/setup.py

I didn't really want to repackage smriprep-docker as more than a single file, so instead I just patched command classes.

FIX: Patch version for smriprep-docker

---

LICENSE

For consistency with fMRIPrep license (see https://github.com/nipreps/fmriprep/pull/3247 and https://github.com/nipreps/fmriprep/pull/3259).

MNT: set copyright owner in LICENSE file

---

smriprep/__main__.py
smriprep/workflows/base.py
smriprep/workflows/fit/registration.py

ISC001 Implicitly concatenated string literals on one line
This rule is currently disabled because it conflicts with the formatter:
https://github.com/astral-sh/ruff/issues/8272

STY: Apply ruff/flake8-implicit-str-concat rule ISC001

---

env.yml

Getting whiplash here.
Spent way too long today trying to fix this upstream:
* https://github.com/conda-forge/ants-feedstock/pull/12
* https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/807

MNT: Unpin libitk 5.3 (ANTs 2.5.3 is built with 5.4)

---

smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py
smriprep/workflows/surfaces.py

This is a supplemental PR to https://github.com/nipreps/nibabies/pull/360 - since nibabies also relies on smriprep, but may be processing in T2w space, this PR generalize many of the workflows/nodes/fields to account for other anatomical references.

RF: Remove much of the hardcoded `T1w` fields in favor of `anat`

---

.circleci/ds005_outputs.txt
smriprep/workflows/outputs.py

This stems from https://github.com/nipreps/nibabies/issues/366.
Changes proposed:
- Add `space-fsaverage` to the filenames of sphere files registering fsnative to fsaverage.

Add `space-fsaverage` to `sphere_reg` output files

---

pyproject.toml
smriprep/workflows/anatomical.py

Testing nipreps/niworkflows#879.

RF: Use genericised "anat" input/output for TemplateDimensions

---

CHANGES.rst
tools/update_changes.sh

Adds the changelog population script

REL: 0.16.0

---

smriprep/workflows/surfaces.py
smriprep/workflows/tests/test_surfaces.py

The segmentation selection code was a bit convoluted, this addresses the following:
- Adding a mapping for common replacements
- Avoiding string iteration
- Stopping iteration over files upon the first match
- Raising FileNotFoundError, rather than an unclear IndexError, if no matches are found.

FIX: Select function in segmentation resampling workflow

---

smriprep/interfaces/templateflow.py

If found, great. If not, just returns `Undefined`.

ENH: Add `t2w_file` output to `TemplateFlowSelect`

---

.circleci/ds005_outputs.txt
src/smriprep/workflows/anatomical.py
src/smriprep/workflows/outputs.py
src/smriprep/workflows/surfaces.py

feat: Output fsLR meshes on subject surfaces

---

.github/workflows/build_test_deploy.yml
CHANGES.rst
pyproject.toml
tox.ini

REL: 0.17.0

---

.github/workflows/build_test_deploy.yml

Hitting 20m timeout. Most runs finish in the 16-17m range, so 30m is a safer indicator that something is actually wrong.

chore(ci): Increase test timeout to 30m (~2x median)

---

src/smriprep/interfaces/fsl.py
src/smriprep/workflows/anatomical.py

This adds a new fsl interface module, which contains a patch for nipype's fast interface. The nipype interface requires bias_iters to be `1 <= integer <= 10`, but setting `bias_iters=0` is required to bypass bias field correction.
The patched interface is dropped into the anatomical workflow and the parameters are accordingly updated.
closes #471

FIX: set fast bias_iters parameter to 0

---

src/smriprep/utils/bids.py

`BIDSLayout` does a `natural_sort` on all `get()` query results, which breaks ordering encoded in the query itself. This PR looks for the label entity in the query and re-sorts by the label list to ensure that values are returned as expected.
A more robust refactor might either carry around a list of tissue labels or re-order probsegs, but doing that right would be a nontrivial effort, and introduce opportunities for new bugs. This narrowly targets a known bug.
This is a bug-fix candidate PR.
Fixes #474.

fix: Respect label order in precomputed derivatives

---

.circleci/ds005_outputs.txt
pyproject.toml
src/smriprep/data/io_spec.json
src/smriprep/workflows/anatomical.py
src/smriprep/workflows/outputs.py
src/smriprep/workflows/surfaces.py

Based on @effigies' idea in https://github.com/nipreps/fmriprep/pull/3491. This new output should make it possible to project data to the surface just using computed derivatives.
Changes proposed:
- Move roi output out of `init_hcp_morphometrics_wf`.
- Calculate that output in a new workflow, `init_cortex_mask_wf`.
- Add step to `init_anat_fit_wf` that calls `init_cortex_mask_wf`.

ENH: Generate cortex mask in anat_fit_wf

---

src/smriprep/utils/bids.py
src/smriprep/utils/tests/test_bids.py

Closes #486.
Changes proposed:
- Create copy of transform queries before updating them. These are the only queries in `collect_derivatives` that are used repeatedly, so they're the only ones we should need a copy of.

FIX: Create copy of query before modifying

---

src/smriprep/workflows/anatomical.py
src/smriprep/workflows/surfaces.py

Adding `init_resample_surfaces_wb_wf`, which is similar to `init_resample_surfaces_wf` but not limited to fsLR spaces.
It can resample surfaces to the specified space and density if the corresponding files exist in TemplateFlow.
For non-fsLR templates, it needs the `space-fsLR` files of the template, which connects the registered sphere (fsLR space) with the template (template space).
For example, with `tpl-onavg_space-fsLR_hemi-L_den-10k_sphere.surf.gii` it can resample the subject's surfaces to `space-onavg_hemi-L_den-10k`.
The code is mostly copied and modified from `init_resample_surfaces_wf`.

Resample surfaces to any space/density using Connectome Workbench.

---

src/smriprep/workflows/base.py

This PR fixes a small typo in the citation boilerplate text
(`sMRIPprep` → `sMRIPrep`) in `smriprep/src/smriprep/workflows/base.py`.
Closes #488.

Fix typo in citation boilerplate (sMRIPprep → sMRIPrep)
