nipreps/smriprep

.circleci/config.yml
Dockerfile
requirements.txt
smriprep/__about__.py
smriprep/workflows/anatomical.py

[PIN] Niworkflows 0.8 and TemplateFlow 0.1

---

requirements.txt
smriprep/__about__.py
smriprep/workflows/anatomical.py

Using the implementation of ``antsBrainExtraction.sh`` from niworkflows
(supersedes #48)

[ENH] Pure Nipype brain extraction workflow

---

.circleci/ds005_outputs.txt
.circleci/ds054_outputs.txt
Dockerfile
requirements.txt
smriprep/__about__.py
smriprep/cli/run.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/outputs.py

This PR closes #6, however leaving two issues open:
- Double check naming and metadata of per-session files (#60)
- Transforms and metadata (#61)
Additionally, this PR exercises poldracklab/niworkflows#308, so it can
be merged should these tests pass.

ENH: Write metadata for anatomical outputs

---

requirements.txt
smriprep/__about__.py
smriprep/cli/run.py
smriprep/cli/utils.py
smriprep/data/boilerplate.bib
smriprep/data/reports/config.json
smriprep/interfaces/reports.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/norm.py
smriprep/workflows/outputs.py

A new spatial normalization workflow has been outsourced from the main
anatomical workflow - closes #1.
This addition is crucial for the implementation of
poldracklab/fmriprep#1558 and more generally, poldracklab/fmriprep#1588.

ENH: Create a spatial normalization workflow

---

requirements.txt
smriprep/__about__.py
smriprep/workflows/anatomical.py
smriprep/workflows/norm.py

ENH: Several improvements over the new spatial normalization workflow

---

requirements.txt
smriprep/__about__.py
smriprep/cli/run.py

these problems arise from latest niworkflows refactor

FIX: Solved problems in report generation

---

smriprep/workflows/outputs.py

ENH: Force compression of derivative NIfTI volumes

---

requirements.txt
smriprep/__about__.py
smriprep/workflows/anatomical.py
smriprep/workflows/norm.py

Refactor the normalization workflow to leverage template specifications

ENH: Pass template specs on to registration workflow 

---

.circleci/config.yml
Dockerfile
requirements.txt
smriprep/__about__.py
smriprep/cli/run.py
smriprep/workflows/norm.py

MAINT: Use PyBIDS 0.9.x via niworkflows PR

---

.circleci/config.yml
MANIFEST.in
long_description.rst
pyproject.toml
requirements.txt
setup.cfg
setup.py
smriprep/__about__.py
smriprep/__init__.py
smriprep/cli/utils.py
smriprep/utils/bids.py

MAINT: Move to setup.cfg + pyproject.toml

---

.circleci/config.yml
smriprep/workflows/anatomical.py

FIX: Render INU-corrected T1w in Segmentation reportlet

---

.circleci/config.yml

Stripped out of #65 to get CI working again.

CI: Fix packaging test

---

.circleci/config.yml
smriprep/cli/run.py
smriprep/workflows/base.py

ENH: Add --fs-subjects-dir flag

---

smriprep/interfaces/freesurfer.py
smriprep/workflows/surfaces.py

Addresses poldracklab/fmriprep#1812.
Do we run a full FreeSurfer in our tests?

FIX: Re-organize FreeSurfer stages to avoid duplication and races

---

docs/conf.py
docs/requirements.txt
smriprep/cli/utils.py
smriprep/interfaces/templateflow.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py
smriprep/workflows/norm.py
smriprep/workflows/outputs.py
smriprep/workflows/surfaces.py

Sets up a build environment like that of niworkflows. @rwblair's finding of napoleon makes the docstring look really nice.

DOC: Revise numpy docstrings so they are correctly rendered

---

.circleci/config.yml
docs/conf.py
smriprep/workflows/base.py
smriprep/workflows/norm.py

DOC: Minimal refactor preparing release

---

smriprep/cli/tests/test_utils.py
smriprep/cli/utils.py
smriprep/conf/__init__.py

Addresses [this problem](https://app.circleci.com/jobs/github/poldracklab/fmriprep/10357) - ref.: poldracklab/fmriprep#1827.

FIX: Allow setting nonstandard spaces for parser

---

README.rst
docs/api.rst
docs/changes.rst
docs/conf.py
docs/index.rst
docs/installation.rst
docs/links.rst
docs/sphinxext/github_link.py
docs/usage.rst
smriprep/workflows/anatomical.py
smriprep/workflows/surfaces.py
wrapper/smriprep_docker.py

DOC: Refactor of documentation

---

CHANGES.rst
setup.cfg

Release 0.4.1

---

.circleci/config.yml
.circleci/nipype.cfg
Dockerfile

Also, simplify the Dockerfile accordingly

MAINT: Revise CircleCI to optimize TemplateFlow and caching

---

smriprep/workflows/norm.py
smriprep/workflows/outputs.py

Getting poldracklab/fmriprep#1955 in a healthy state.

ENH: Fix template keys output in normalization workflow, when cohort present

---

docs/usage.rst
setup.cfg
smriprep/cli/run.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py

hopefully the last refactor of these new objects 😅 
get in accordance with https://github.com/poldracklab/niworkflows/pull/457

rf: update Spaces objects

---

setup.cfg
smriprep/cli/run.py
smriprep/interfaces/freesurfer.py
smriprep/workflows/surfaces.py

Which seems to have enabled some other warnings that were ignored by default.

MAINT: Add ignore W503 in setup.cfg

---

setup.cfg
smriprep/cli/run.py
smriprep/workflows/anatomical.py
smriprep/workflows/base.py

ENH: Add option to skip brain extraction

---

smriprep/data/io_spec.json
smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py

FIX: Make TPMs label ordering in ``io_spec.json`` consistent with workflow

---

setup.cfg
smriprep/cli/run.py

ENH: use fs canary to detect license issues

---

smriprep/interfaces/__init__.py

MAINT: Remove unused nwf interfaces

---

smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py

FIX: Convert LTA to ITK with nitransforms

---

setup.cfg
smriprep/workflows/anatomical.py
smriprep/workflows/outputs.py

Stealing a title from #223. Testing nipreps/niworkflows#547.
Closes #197.

ENH: Retain session info when multi-session data are not averaged

---

.circleci/config.yml

Porting over https://github.com/nipreps/fmriprep/pull/2316 where the `machine` executor is used.

CI: CircleCI housekeeping

---

Dockerfile
docs/requirements.txt
setup.cfg
smriprep/interfaces/reports.py
smriprep/workflows/anatomical.py
smriprep/workflows/norm.py
smriprep/workflows/outputs.py

MAINT: Update to new API of *NiWorkflows*

---

.circleci/config.yml
wrapper/smriprep_docker.py

Following what was implemented in fmriprep:
- Add Docker orb for easy authentication
- Bump machine images to latest LTS (focal)
- Remove setfacl calls

MAINT: CircleCI housekeeping

---

.circleci/config.yml

MAINT: Use PAT for docker login

---

setup.cfg
smriprep/workflows/anatomical.py

FIX: Revert to FAST for tissue probability maps

---

smriprep/workflows/anatomical.py
smriprep/workflows/norm.py

- Start headers with a newline
- Clean up punctuation when listing templates

FIX: Lingering boilerplate fixes

---

Dockerfile
scripts/fetch_templates.py

Related to https://github.com/nipreps/fmriprep/pull/2647

DOCKER: Update Dockerfile to match fMRIPrep, using FSL 6 for testing

---

CHANGES.rst
Dockerfile
setup.cfg

Preparing release following the new niworkflows series.
Bumping nipype since FS7 recon-all support was added

REL: 0.9.0

---

docker/files/freesurfer7.2-exclude.txt

FIX: Re-add fsr-checkxopts to Docker image

---

docker/files/freesurfer7.2-exclude.txt
docs/conf.py

FIX: Re-add missing getfullpath FreeSurfer binary

---

.zenodo.json
CHANGES.rst
setup.cfg
wrapper/smriprep_docker.py

Prep for release series to support fMRIPrep 22.1.x and nibabies 22.2.x.
@ericfeczko Would you mind checking your affiliation information so we properly credit you?

REL: 0.10.0

---

.circleci/config.yml
Dockerfile

CI: Prioritize tags on release

---

setup.cfg

To allow tests / compatibility with the latest

DEP: Loosen niworkflow restriction

---

.github/workflows/pythonpackage.yml
setup.cfg

Test with Python 3.11, show Python 3.11 as supported.

MNT: Python 3.11 should be supported

---

smriprep/workflows/outputs.py

Woops. Thanks to @shotgunosine for noticing that the outputs looked suspiciously similar.

FIX: Pass sphere_reg_fsLR to ds_reg_fsLR

---

.circleci/config.yml
.circleci/pytest.sh

We don't currently run tests in an environment with everything installed.

ENH: Run pytest on CircleCI

---

smriprep/data/io_spec.json
smriprep/utils/bids.py

add missing fsLR reg sphere to io_spec

---

.git-blame-ignore-revs
.github/workflows/build_test_deploy.yml
Makefile
pyproject.toml
src/smriprep/interfaces/templateflow.py
src/smriprep/utils/bids.py
src/smriprep/workflows/anatomical.py
src/smriprep/workflows/outputs.py
src/smriprep/workflows/surfaces.py

Checking whether https://github.com/astral-sh/uv/issues/5450 is resolved.

chore: Unpin build-and-inspect-python-package
